mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from polls.views import IndexView

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', IndexView.as_view(), name='home'),
    #path('', TemplateView.as_view(template_name='index.html'), name='home'),
    #path('polls/', TemplateView.as_view(template_name='polls/index.html'), name='home'),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('person_search/', views.person_query, name='ihmiset'),

]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Person(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    SoSec_number = models.CharField(max_length=200)
    def __str__(self):
        return self.first_name + ' ' + self.last_name + ' ' + self.SoSec_number

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice, Person
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.views import generic
from django.views.generic import TemplateView, ListView
import http.client
import json


class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def person_query(request):
    query = 'SELECT * FROM polls_person WHERE polls_person.first_name LIKE  "%s"' % request.GET['first_name']
    model_items = Person.objects.raw(query)
    #if 'first_name' in request.GET and 'last_name' in request.GET:
    #    query = 'SELECT * FROM polls_person WHERE polls_person.first_name LIKE  "%s"' % request.GET['first_name']
       # model_items = Person.objects.raw(query)
        #print(Person.objects.raw(query))
    #else:
       # model_items = Person.objects.all()
    return render(request, 'person_query.html', {'model_items': model_items})
    #return redirect(request.META['HTTP_REFERER'])

mysite/polls/templates/base.html
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

mysite/polls/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

mysite/polls/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<h2>Voting info</h2>
<html lang="en-AU">
<body>
<form method="get">
    <label for="query">Search: </label>
    <input type="text" id="query" name="query" />
    <input type="submit" value="Search" />
</form>

<span id="search-query" ></span>

<script type="application/javascript">
    var searchParams = new URLSearchParams(document.location.search);
    if (searchParams.has("query"))
    {
        document.getElementById("search-query").innerHTML = "You searched for " + searchParams.get("query")
    }
</script>
</body>
</html>
<h3>Voter info</h3>
<html xmlns="http://www.w3.org/1999/xhtml">
    <html lang="en-AU">
<html>
  <form method="get" action="{% url 'polls:ihmiset' %}">
    <input type="text" name="first_name" />
    <input type="submit" value="Search" />
  </form>
</html>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

mysite/polls/templates/person_query.html
<h3>Voter info</h3>
<html xmlns="http://www.w3.org/1999/xhtml">
    <html lang="en-AU">
<html>
  <form method="get" action="{% url 'polls:ihmiset' %}">
    <input type="text" name="first_name" />
    <input type="submit" value="Search" />
  </form>
  <table>
    <thead>
      <tr>
        <th>First name</th>
        <th>Surname</th>
      <tr>
    </thead>
    <tbody>
    {% for item in model_items %}
      <tr>
        <td>{{ item.first_name }}</td>
        <td>{{ item.last_name }}</td>
          <td>{{item.SoSec_number}}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</html>

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/results.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
Hi {{ user.username }}!
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}